<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Warrior_plus_ipn extends CI_Controller
{
    
    function __construct()
    {
        parent::__construct();
		$this->load->model('package/Order_Model');
		$this->load->model('package/Mailsending_Model');
		$this->tableUser='tbl_user';	
		//$this->wpSecretKey=config_item('warriorplus_secret_key');	
		$this->wpSecretKey=config_item('warriorplus_secret_key');	

        
    }
    public function index()
    {
       
		// WP_ITEM_NAME - Product name entered in WarriorPlus
		// WP_ITEM_NUMBER - Item number generated by WarriorPlus (unique to this productr)
		// WP_BUYER_NAME - First and last name of the buyer
		// WP_BUYER_EMAIL - Email address of the buyer
		// WP_SALE_AMOUNT - Price the buyer paid
		// WP_SALE_CURRENCY - Currency the buyer paid with (currently always USD)
		// WP_TXNID - Payment processor generated transaction id of the sale
		// WP_SALEID - WarriorPlus generated sale id (unique to this sale)
		// WP_AFFID - WarriorPlus unique affiliate id of referring affiliate (if applicable)
		// WP_PAYMETHOD - Payment method used (ie paypal, stripe, free, wallet)
		// WP_ACTION - Action related to this IPN message (currently 'sale' or 'refund')
		// WP_SECURITYKEY - If set in your account settings, this will be sent so you can validate the authenticity of the IPN message
		
		
		
			/*$_POST['WP_ACTION']='sale';
    $_POST['WP_SALE']='sale';
    $_POST['WP_ITEM_NAME']='AI TubeStar Special';
    $_POST['WP_ITEM_NUMBER']='wso_wjsqnc';
    $_POST['WP_BUYER_NAME']='Abhi';
    $_POST['WP_BUYER_EMAIL']='maheshsuman7600@gmail.com';
    $_POST['WP_BUYER_IP']='103.133.123.59';
    $_POST['WP_SALE_AMOUNT']='1.00';
    $_POST['WP_SALE_CURRENCY']='USD';
    $_POST['WP_TXNID']='5AF84518TJ688220A';
    $_POST['WP_SALEID']='10931401';
    $_POST['WP_AFFUSER']='';
    $_POST['WP_AFFID']='';
    $_POST['WP_SID']='test';
    $_POST['WP_PAYMETHOD']='ppm';
    $_POST['WP_PAYMENT_STATUS']='COMPLETED';
    $_POST['WP_SALE_EARNINGS_VENDOR']='0.85';
    $_POST['WP_SALE_EARNINGS_WPFEE']='0.15';
    $_POST['WP_SALE_FEE']='0.15';
    $_POST['WP_BUYER_FIRSTNAME']='mahesh';
    $_POST['WP_BUYER_LASTNAME']='mahesh';
    $_POST['IPN_ID']='df192ea1e447024f415308565bdcdd279c29ccc4fdf17593f13b21260bc5fdd6';
    $_POST['IPN_RCPT_TYPE']='vend';
    $_POST['WP_SECURITYKEY']=config_item('warriorplus_secret_key'); */
		
		
		
		
		$this->db->set('type','wp');
		$this->db->set('description',json_encode($_POST));
		$this->db->insert('ipn_testing_hold');
		
		//$response = $this->warriorPlusIpnVerification();
		//echo $response;
		//die('its working fine');
		// $response = 1;
		$secretKey = $this->wpSecretKey;
        if ($_POST['WP_SECURITYKEY']==$secretKey) {
            
			$_POST['transaction_from'] = 'wp';
            $transaction_id = $this->Order_Model->addWarriorPlusTransaction();
            
            // CHECK IF USER ALREADY EXISTS and SET FLAG
			$name = $_POST['WP_BUYER_NAME'];
			$email = $_POST['WP_BUYER_EMAIL'];
			$product_id = $_POST['WP_ITEM_NUMBER'];
			$title = $_POST['WP_ITEM_NAME'];
            $user_exists = $this->Order_Model->checkUserExist($_POST['WP_BUYER_EMAIL']);
            
            
            if ($_POST['WP_ACTION'] == 'SALE' || $_POST['WP_ACTION'] == 'sale') {
                
                if (!$user_exists) {
					$password = $this->generateRandomString();
					$passwordN =md5($password);
					
                    $user_id = $this->Order_Model->addUser($email,$passwordN,$name);
						
					$title = $this->Common_Modal->getSingleFieldFromAnyTable('title','wp_product_id',$product_id,'tbl_package_plans');
					$level = $this->Common_Modal->getSingleFieldFromAnyTable('sell_type','wp_product_id',$product_id,'tbl_package_plans');
				 	$ReplaceArray['name'] = $name;
				    $ReplaceArray['email'] = $email;
				    $ReplaceArray['login_url'] = site_url();
				    $ReplaceArray['password'] = $password;
					$ReplaceArray['plan_name'] = $title;				
					
					
					$registrationTemplate = $this->Order_Model->getEmailTemplateDetail('jvz-registration-email');
				    $registrationsubject = $registrationTemplate->subject;
				    $registrationmessage = $this->Common_Modal->replaceEmailTags($registrationTemplate->message,$ReplaceArray);
					if($registrationTemplate->message!='')
				    $this->Mailsending_Model->sendmail($registrationsubject,$registrationmessage,$email);
					
					$planTemplate = $this->Order_Model->getEmailTemplateDetail($level);
				    $plansubject = $planTemplate->subject;
				    $planmessage = $this->Common_Modal->replaceEmailTags($planTemplate->message,$ReplaceArray);
					if($planTemplate->message!='')
				    $this->Mailsending_Model->sendmail($plansubject,$planmessage,$email); 
					
                }
                else {
                    $user_id = $this->Common_Modal->getSingleFieldFromAnyTable('id','email',$_POST['WP_BUYER_EMAIL'],$this->tableUser);
					$this->Order_Model->changeUserStatus($user_id,'1');
					$title = $this->Common_Modal->getSingleFieldFromAnyTable('title','wp_product_id',$product_id,'tbl_package_plans');
					$level = $this->Common_Modal->getSingleFieldFromAnyTable('sell_type','wp_product_id',$product_id,'tbl_package_plans');
					
					$ReplaceArray['name'] = $name;
				    $ReplaceArray['email'] = $email;
					$ReplaceArray['plan_name'] = $title;

					$planTemplate = $this->Order_Model->getEmailTemplateDetail($level);
				    $plansubject = $planTemplate->subject;
				    $planmessage = $this->Common_Modal->replaceEmailTags($planTemplate->message,$ReplaceArray);
				
					if($planTemplate->message!='')
				    $this->Mailsending_Model->sendmail($plansubject,$planmessage,$email); 
				}
				
                $purchase_id = $this->Order_Model->addPackagePurchaseWP($user_id,$transaction_id,$_POST['WP_ITEM_NUMBER']);
				$this->Order_Model->updateTransaction($transaction_id,$purchase_id,$user_id);
				$packageDetail = $this->Order_Model->getPackageDetailWp($_POST['WP_ITEM_NUMBER']);
				$data['price']   =   $_POST['WP_SALE_AMOUNT'];
			    $data['package_id'] = $packageDetail->id;
			    $data['user_id'] = $user_id;
				$data['user_email'] = $_POST['WP_BUYER_EMAIL'];
			    $data['payment_mode']         =   'WP';
			    $data['payment_status']         =   'complete';
			    $data['trans_id']         =   $transaction_id;
			    $data['purchase_id']         =   $purchase_id;
				$order_id =  $this->Order_Model->addPackageOrder($data);
				
				$this->setUserPackage($user_id);
				
				
            }
         if ($user_exists) {
            if ($_POST['WP_ACTION'] == 'refund' || $_POST['WP_ACTION'] == 'RFND') { 
			   $user_id = $this->Common_Modal->getSingleFieldFromAnyTable('id','email',$_POST['WP_BUYER_EMAIL'],$this->tableUser);
			   $this->Order_Model->changeWPPackageStatus($user_id,$_POST['WP_ITEM_NUMBER'],'inactive');
			   $purchase_id = $this->Order_Model->getWPPurchaseId($user_id,$_POST['WP_ITEM_NUMBER']);
			   $this->Order_Model->updateTransaction($transaction_id,$purchase_id,$user_id);
			      
			   $this->db->select('id');
			   $this->db->where('user_id',$user_id);
			   $this->db->where('status','active');
			   $query1 = $this->db->get('tbl_package_purchase');
			   $rCount = $query1->num_rows();
			   if($rCount==0)
			   $this->Order_Model->changeUserStatus($user_id,'0');
			   $this->setUserPackage($user_id);
			   
				$ReplaceArray['name'] = $name;
				$ReplaceArray['email'] = $email;
				$ReplaceArray['plan_name'] = $title;
				$planTemplate = $this->Order_Model->getEmailTemplateDetail('refund');
				$plansubject = $planTemplate->subject;
				$planmessage = $this->Common_Modal->replaceEmailTags($planTemplate->message,$ReplaceArray);
			
				 if($planTemplate->message!='')
				 $this->Mailsending_Model->sendmail($plansubject,$planmessage,$email);
			 
			 
			 
			}
			
			if ($_POST['WP_ACTION'] == 'BILL') {
                
                $user_id = $this->Common_Modal->getSingleFieldFromAnyTable('id','email',$_POST['WP_BUYER_EMAIL'],$this->tableUser);
				$this->Order_Model->changeUserStatus($user_id,'1');

                $purchase_id = $this->Order_Model->addPackagePurchaseJVZ($user_id,$transaction_id,$_POST['WP_ITEM_NUMBER']);
				$this->Order_Model->updateTransaction($transaction_id,$purchase_id,$user_id);
				$packageDetail = $this->Order_Model->getPackageDetail($_POST['WP_ITEM_NUMBER']);
				$data['price']   =   $_POST['WP_SALE_AMOUNT'];
			    $data['package_id'] = $packageDetail->id;
			    $data['user_id'] = $user_id;
				$data['user_email'] = $_POST['WP_BUYER_EMAIL'];
			    $data['payment_mode']         =   'WP';
			    $data['payment_status']         =   'complete';
			    $data['trans_id']         =   $transaction_id;
			    $data['purchase_id']         =   $purchase_id;
				$order_id =  $this->Order_Model->addPackageOrder($data);
				
				$this->setUserPackage($user_id);
				
				$title = $this->Common_Modal->getSingleFieldFromAnyTable('title','wp_product_id',$product_id,'tbl_package_plans');
					
				$ReplaceArray['name'] = $name;
				$ReplaceArray['email'] = $email;
				$ReplaceArray['plan_name'] = $title;

				$planTemplate = $this->Order_Model->getEmailTemplateDetail('bill');
				$plansubject = $planTemplate->subject;
				$planmessage = $this->Common_Modal->replaceEmailTags($planTemplate->message,$ReplaceArray);
				if($planTemplate->message!='')
				$this->Mailsending_Model->sendmail($plansubject,$planmessage,$email);
				
				
            }
			if ($_POST['WP_ACTION'] == 'CANCEL-REBILL') { 
			   $user_id = $this->Common_Modal->getSingleFieldFromAnyTable('id','email',$_POST['WP_BUYER_EMAIL'],$this->tableUser);
			   $this->Order_Model->changePackageStatus($user_id,$_POST['WP_ITEM_NUMBER'],'inactive');
			   $purchase_id = $this->Order_Model->getWPPurchaseId($user_id,$_POST['WP_ITEM_NUMBER']);
			   $this->Order_Model->updateTransaction($transaction_id,$purchase_id,$user_id);
			      
			   $this->db->select('id');
			   $this->db->where('user_id',$user_id);
			   $this->db->where('status','active');
			   $query1 = $this->db->get('tbl_package_purchase');
			   $rCount = $query1->num_rows();
			   if($rCount==0)
			   $this->Order_Model->changeUserStatus($user_id,'0');
			   $this->setUserPackage($user_id);
			   
			   $title = $this->Common_Modal->getSingleFieldFromAnyTable('title','wp_product_id',$product_id,'tbl_package_plans');
					
			   $ReplaceArray['name'] = $name;
			   $ReplaceArray['email'] = $email;
			   $ReplaceArray['plan_name'] = $title;

			   $planTemplate = $this->Order_Model->getEmailTemplateDetail('cancel-bill');
			   $plansubject = $planTemplate->subject;
			   $planmessage = $this->Common_Modal->replaceEmailTags($planTemplate->message,$ReplaceArray);
			   if($planTemplate->message!='')
			   $this->Mailsending_Model->sendmail($plansubject,$planmessage,$email);
				
			}
		  }
        }
	}
	
    function generateRandomString($length = 10)
    {
        $characters       = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $charactersLength = strlen($characters);
        $randomString     = '';
        for ($i = 0; $i < $length; $i++) {
            $randomString .= $characters[rand(0, $charactersLength - 1)];
        }
        return $randomString;
    }
	function setUserPackage($user_id)
	{
	   $this->load->model('package/Package_purchase_Model');
	   $user_package = $this->Package_purchase_Model->checkForPackage($user_id);
	   $this->Order_Model->updateUserPackage($user_id,$user_package);
	}
}