<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit56c4210aa2c53a68c8aa753a5cbc7cec
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'Orhanerday\\OpenAi\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Orhanerday\\OpenAi\\' => 
        array (
            0 => __DIR__ . '/..' . '/orhanerday/open-ai/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit56c4210aa2c53a68c8aa753a5cbc7cec::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit56c4210aa2c53a68c8aa753a5cbc7cec::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit56c4210aa2c53a68c8aa753a5cbc7cec::$classMap;

        }, null, ClassLoader::class);
    }
}
