<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInita4d90da15e2919fefdc2a43277151b51
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'Orhanerday\\OpenAi\\' => 18,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Orhanerday\\OpenAi\\' => 
        array (
            0 => __DIR__ . '/..' . '/orhanerday/open-ai/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInita4d90da15e2919fefdc2a43277151b51::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInita4d90da15e2919fefdc2a43277151b51::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInita4d90da15e2919fefdc2a43277151b51::$classMap;

        }, null, ClassLoader::class);
    }
}
